### ISSUE TITLE
ELK 설정 config

### ISSUE THREAD

**Issue by hmu332233** [hmu332233/tips#22]
### 개요

```
filebeat -> logstash -> elasticsearch
```
filebeat: 파일 서빙 역할
logstash: 파일 파싱 역할

### filebeat

```
filebeat:
  inputs:
    - type: log
      enabled: true
      paths:
        - /log/example.log*
      fields:
        service: example-log
      fields_under_root: true

output:
  logstash:
    hosts: ["0.0.0.0:5044"]
```

### logstash
```
filter {
	if [service] == "example-log" {
		json {
			source => "message"
		}

		date {
			match => ["time", "yyyy-MM-dd'T'HH:mm:ss.SSSZ"]
			target => "@timestamp"
		}
	}
}
output {
        if [service] == "example-log" {
                elasticsearch {
                        hosts => ["http://0.0.0.0:9200"]
			index => ["example-log-%{+YYYY.MM.dd}"]
               		user => "user"
                        password => "password"
		}
        }
}
```
