### ISSUE TITLE
github action

### ISSUE THREAD

**Issue by hmu332233** [hmu332233/tips#33]
## 다른 디렉토리에서 동작하기
`working-directory` 이용
```
- name: Install
  run: yarn install
  working-directory: ${{ env.WORKING_DIRECTORY }}
- name: Run
  run: yarn start
  env:
    DB_URL: ${{ secrets.DB_URL }}
  working-directory: ${{ env.WORKING_DIRECTORY }}
```

[내 레포에서 사용 예시](https://github.com/hmu332233/LetMeKnow.jbnu--lambda/blob/master/.github/workflows/parseFood.yml)

## 캐싱

`actions/cache@v2` 이용
id 값을 통해서 output 값에 접근도 가능함, 예시에서는 steps.cache.outputs.cache-hit 값으로 캐싱된게 있는지 체크 가능
```
- name: Cache node modules
  uses: actions/cache@v2
  id: cache # 해당 step을 대표하는 id
  with:
    path: ${{ env.WORKING_DIRECTORY }}/node_modules
    key: ${{ runner.os }}-yarn-parse-${{ hashFiles('**/yarn.lock') }}
    restore-keys: |
      ${{ runner.os }}-yarn-parse-
```

[내 레포에서 사용 예시](https://github.com/hmu332233/LetMeKnow.jbnu--lambda/blob/master/.github/workflows/parseFood.yml)
